spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tikkit_db
    username: tikkit_user
    password: tikkit_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true