-- MVP 초기 스키마 (docs/ERD.md 1절 참조)

CREATE TABLE venues (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(100) NOT NULL,
    address    varchar(255) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_venues_name UNIQUE (name)
);

CREATE TABLE members (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(255) NOT NULL,
    password   varchar(100) NOT NULL,
    name       varchar(50)  NOT NULL,
    phone      varchar(20)  NOT NULL,
    role       varchar(20)  NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_members_email ON members (lower(email));

CREATE TABLE performances (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           varchar(200) NOT NULL,
    category        varchar(20)  NOT NULL CHECK (category IN ('CONCERT', 'MUSICAL', 'THEATER', 'CLASSIC', 'SPORTS')),
    description     text,
    poster_url      varchar(500),
    venue_id        bigint       NOT NULL REFERENCES venues (id),
    running_minutes int          NOT NULL,
    age_rating      varchar(20)  NOT NULL,
    start_date      date,
    end_date        date,
    status          varchar(20)  NOT NULL CHECK (status IN ('UPCOMING', 'ON_SALE', 'CLOSED')),
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_performances_status_start_date ON performances (status, start_date);

CREATE TABLE schedules (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id   bigint      NOT NULL REFERENCES performances (id),
    show_at          timestamptz NOT NULL,
    booking_open_at  timestamptz NOT NULL,
    booking_close_at timestamptz NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_schedules_performance_show_at UNIQUE (performance_id, show_at),
    CONSTRAINT ck_schedules_booking_window CHECK (booking_open_at < booking_close_at AND booking_close_at <= show_at)
);

CREATE TABLE ticket_grades (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id        bigint       NOT NULL REFERENCES schedules (id),
    grade              varchar(10)  NOT NULL CHECK (grade IN ('VIP', 'R', 'S', 'A')),
    price              numeric(12, 0) NOT NULL CHECK (price >= 0),
    total_quantity     int          NOT NULL,
    remaining_quantity int          NOT NULL,
    created_at         timestamptz  NOT NULL DEFAULT now(),
    updated_at         timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_ticket_grades_schedule_grade UNIQUE (schedule_id, grade),
    CONSTRAINT uk_ticket_grades_id_schedule UNIQUE (id, schedule_id),
    CONSTRAINT ck_ticket_grades_remaining_range CHECK (0 <= remaining_quantity AND remaining_quantity <= total_quantity)
);

CREATE TABLE reservations (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_no  varchar(20)  NOT NULL,
    member_id       bigint       NOT NULL REFERENCES members (id),
    schedule_id     bigint       NOT NULL REFERENCES schedules (id),
    ticket_grade_id bigint       NOT NULL,
    quantity        smallint     NOT NULL CHECK (quantity BETWEEN 1 AND 4),
    unit_price      numeric(12, 0) NOT NULL,
    total_amount    numeric(12, 0) NOT NULL,
    status          varchar(20)  NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
    expires_at      timestamptz,
    confirmed_at    timestamptz,
    cancelled_at    timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_reservations_reservation_no UNIQUE (reservation_no),
    CONSTRAINT ck_reservations_total_amount CHECK (total_amount = unit_price * quantity),
    CONSTRAINT fk_reservations_ticket_grade_schedule
        FOREIGN KEY (ticket_grade_id, schedule_id) REFERENCES ticket_grades (id, schedule_id)
);
CREATE INDEX idx_reservations_member_created_at ON reservations (member_id, created_at DESC);
CREATE INDEX idx_reservations_pending_expires_at ON reservations (expires_at) WHERE status = 'PENDING';

CREATE TABLE payments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  bigint       NOT NULL REFERENCES reservations (id),
    amount          numeric(12, 0) NOT NULL,
    method          varchar(20)  NOT NULL CHECK (method IN ('CARD', 'KAKAO_PAY', 'BANK_TRANSFER')),
    status          varchar(20)  NOT NULL CHECK (status IN ('PAID', 'REFUNDED')),
    transaction_key varchar(64)  NOT NULL,
    paid_at         timestamptz,
    refunded_at     timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_payments_reservation_id UNIQUE (reservation_id),
    CONSTRAINT uk_payments_transaction_key UNIQUE (transaction_key)
);

-- 한국어 COMMENT (docs/ERD.md 1절과 동일)

COMMENT ON COLUMN venues.id IS '고유 식별자(PK)';
COMMENT ON COLUMN venues.created_at IS '생성 일시';
COMMENT ON COLUMN venues.updated_at IS '수정 일시';
COMMENT ON TABLE venues IS '공연장 정보';
COMMENT ON COLUMN venues.name IS '공연장 이름';
COMMENT ON COLUMN venues.address IS '공연장 주소';

COMMENT ON COLUMN members.id IS '고유 식별자(PK)';
COMMENT ON COLUMN members.created_at IS '생성 일시';
COMMENT ON COLUMN members.updated_at IS '수정 일시';
COMMENT ON TABLE members IS '회원 정보';
COMMENT ON COLUMN members.email IS '로그인에 사용하는 이메일(로그인 ID), 대소문자 구분 없이 유일';
COMMENT ON COLUMN members.password IS 'BCrypt로 암호화된 비밀번호';
COMMENT ON COLUMN members.name IS '회원 이름';
COMMENT ON COLUMN members.phone IS '휴대폰 번호';
COMMENT ON COLUMN members.role IS '권한 구분 (USER: 일반 회원, ADMIN: 관리자)';

COMMENT ON COLUMN performances.id IS '고유 식별자(PK)';
COMMENT ON COLUMN performances.created_at IS '생성 일시';
COMMENT ON COLUMN performances.updated_at IS '수정 일시';
COMMENT ON TABLE performances IS '공연 정보 (뮤지컬·콘서트 등 하나의 작품 단위)';
COMMENT ON COLUMN performances.title IS '공연명';
COMMENT ON COLUMN performances.category IS '공연 분류 (CONCERT/MUSICAL/THEATER/CLASSIC/SPORTS)';
COMMENT ON COLUMN performances.description IS '공연 상세 설명';
COMMENT ON COLUMN performances.poster_url IS '포스터 이미지 URL';
COMMENT ON COLUMN performances.venue_id IS '공연이 열리는 공연장 (venues 참조)';
COMMENT ON COLUMN performances.running_minutes IS '공연 러닝타임(분)';
COMMENT ON COLUMN performances.age_rating IS '관람 연령 등급';
COMMENT ON COLUMN performances.start_date IS '전체 공연 기간 시작일 (schedules로부터 파생, 배치가 재계산)';
COMMENT ON COLUMN performances.end_date IS '전체 공연 기간 종료일 (schedules로부터 파생, 배치가 재계산)';
COMMENT ON COLUMN performances.status IS '판매 상태 (UPCOMING/ON_SALE/CLOSED, 배치가 재계산하는 파생값)';

COMMENT ON COLUMN schedules.id IS '고유 식별자(PK)';
COMMENT ON COLUMN schedules.created_at IS '생성 일시';
COMMENT ON COLUMN schedules.updated_at IS '수정 일시';
COMMENT ON TABLE schedules IS '공연 회차 (같은 공연이라도 날짜·시간별로 별도 판매 단위)';
COMMENT ON COLUMN schedules.performance_id IS '소속 공연 (performances 참조)';
COMMENT ON COLUMN schedules.show_at IS '공연 실제 시작 일시';
COMMENT ON COLUMN schedules.booking_open_at IS '예매 시작 일시';
COMMENT ON COLUMN schedules.booking_close_at IS '예매 마감 일시';

COMMENT ON COLUMN ticket_grades.id IS '고유 식별자(PK)';
COMMENT ON COLUMN ticket_grades.created_at IS '생성 일시';
COMMENT ON COLUMN ticket_grades.updated_at IS '수정 일시';
COMMENT ON TABLE ticket_grades IS '회차별 좌석 등급 및 가격·재고 (MVP는 지정석 없이 등급별 수량으로만 관리)';
COMMENT ON COLUMN ticket_grades.schedule_id IS '소속 회차 (schedules 참조)';
COMMENT ON COLUMN ticket_grades.grade IS '좌석 등급 (VIP/R/S/A)';
COMMENT ON COLUMN ticket_grades.price IS '등급별 판매 가격 (원)';
COMMENT ON COLUMN ticket_grades.total_quantity IS '등급별 총 판매 수량';
COMMENT ON COLUMN ticket_grades.remaining_quantity IS '잔여 수량. total_quantity에서 활성 예약 수량 합을 뺀 값과 항상 같아야 하며, 동시성 제어(조건부 UPDATE)의 대상이라 인덱스를 걸지 않는다';

COMMENT ON COLUMN reservations.id IS '고유 식별자(PK)';
COMMENT ON COLUMN reservations.created_at IS '생성 일시';
COMMENT ON COLUMN reservations.updated_at IS '수정 일시';
COMMENT ON TABLE reservations IS '예매 내역 (좌석 선점부터 결제·취소·만료까지의 상태를 관리)';
COMMENT ON COLUMN reservations.reservation_no IS '사용자에게 노출되는 예매번호 (TK{yyMMdd}-{6자리})';
COMMENT ON COLUMN reservations.member_id IS '예매한 회원 (members 참조)';
COMMENT ON COLUMN reservations.schedule_id IS '예매 대상 회차 (schedules 참조). ticket_grade_id를 거치지 않고 회차별 예약을 바로 조회하기 위한 의도적 중복 경로';
COMMENT ON COLUMN reservations.ticket_grade_id IS '예매한 좌석 등급 (ticket_grades 참조)';
COMMENT ON COLUMN reservations.quantity IS '예매 매수 (1~4매)';
COMMENT ON COLUMN reservations.unit_price IS '예매 시점의 등급별 단가 스냅샷 (이후 가격이 바뀌어도 예약 금액은 유지)';
COMMENT ON COLUMN reservations.total_amount IS '총 결제 금액 (unit_price * quantity와 항상 일치, CHECK 제약으로 보장)';
COMMENT ON COLUMN reservations.status IS '예매 상태 (PENDING/CONFIRMED/CANCELLED/EXPIRED)';
COMMENT ON COLUMN reservations.expires_at IS '선점 만료 시각 (PENDING 상태에서 이 시각이 지나면 스케줄러가 EXPIRED 처리)';
COMMENT ON COLUMN reservations.confirmed_at IS '결제 완료(확정) 시각';
COMMENT ON COLUMN reservations.cancelled_at IS '취소 처리 시각';

COMMENT ON COLUMN payments.id IS '고유 식별자(PK)';
COMMENT ON COLUMN payments.created_at IS '생성 일시';
COMMENT ON COLUMN payments.updated_at IS '수정 일시';
COMMENT ON TABLE payments IS '결제 내역 (예매 1건당 결제 1건, 모의 결제)';
COMMENT ON COLUMN payments.reservation_id IS '결제 대상 예매 (reservations 참조, 1:1)';
COMMENT ON COLUMN payments.amount IS '결제 금액 (원)';
COMMENT ON COLUMN payments.method IS '결제 수단 (CARD/KAKAO_PAY/BANK_TRANSFER)';
COMMENT ON COLUMN payments.status IS '결제 상태 (PAID/REFUNDED)';
COMMENT ON COLUMN payments.transaction_key IS '결제 거래 고유 키 (모의 결제에서는 UUID)';
COMMENT ON COLUMN payments.paid_at IS '결제 완료 시각';
COMMENT ON COLUMN payments.refunded_at IS '환불 처리 시각';
