-- 지정석 전환 expand 단계 (docs/ERD.md 2절 참조, Task 021)
-- 기존 테이블은 건드리지 않는다 — 좌석을 모르는 현재 애플리케이션이 그대로 동작해야 한다.
-- ticket_grades의 수량 컬럼 제거는 V6(contract, Task 022)에서 한다.

CREATE TABLE seats (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id    bigint      NOT NULL REFERENCES venues (id),
    section     varchar(10) NOT NULL,
    row_label   varchar(5)  NOT NULL,
    seat_number int         NOT NULL CHECK (seat_number >= 1),
    pos_x       int         NOT NULL,
    pos_y       int         NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_seats_venue_section_row_number UNIQUE (venue_id, section, row_label, seat_number)
);
-- venue_id 단독 인덱스를 따로 만들지 않는다 — uk_seats_venue_section_row_number의 선두 컬럼이
-- venue_id라서 "공연장의 전체 좌석" 조회가 그 인덱스를 그대로 탄다.
-- row_label은 varchar지만 알파벳이 아니라 숫자 문자열('1', '2', ... '23')을 담는다.
-- 국내 예매처 관행이 "3열 12번"이고, 숫자를 쓰면 백필에서 27열 이상을 'AA'로 넘기는 분기도 없어진다.

CREATE TABLE schedule_seats (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id     bigint      NOT NULL REFERENCES schedules (id),
    seat_id         bigint      NOT NULL REFERENCES seats (id),
    ticket_grade_id bigint      NOT NULL,
    status          varchar(10) NOT NULL CHECK (status IN ('AVAILABLE', 'HELD', 'SOLD')),
    reservation_id  bigint      REFERENCES reservations (id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_schedule_seats_schedule_seat UNIQUE (schedule_id, seat_id),
    CONSTRAINT fk_schedule_seats_ticket_grade_schedule
        FOREIGN KEY (ticket_grade_id, schedule_id) REFERENCES ticket_grades (id, schedule_id),
    CONSTRAINT ck_schedule_seats_status_holder CHECK (
        (status = 'AVAILABLE' AND reservation_id IS NULL)
        OR (status IN ('HELD', 'SOLD') AND reservation_id IS NOT NULL))
) WITH (fillfactor = 90);
-- idx(schedule_id, status)와 idx(reservation_id)를 의도적으로 두지 않는다 (docs/ERD.md 2절).
-- 모든 선점/해제가 status와 reservation_id를 갱신하므로, 인덱스가 있으면 매번 인덱스 엔트리를
-- 다시 써야 해서 HOT(Heap-Only Tuple) 업데이트를 못 쓴다. 좌석맵 조회(WHERE schedule_id = ?)는
-- uk_schedule_seats_schedule_seat로 충분하고, 좌석 해제는 reservation_seats를 경유한다.
--
-- fillfactor 90은 그 "인덱스 없음"의 전제 조건이다. 인덱스가 없어도 페이지에 빈 공간이 없으면
-- 새 튜플이 다른 페이지로 넘어가 HOT이 깨진다. CREATE TABLE 시점에만 깔끔하게 걸 수 있다
-- (나중에 ALTER TABLE로 바꾸면 이미 쓰인 페이지에는 적용되지 않아 VACUUM FULL이 필요하다).
--
-- ck_schedule_seats_status_holder: AVAILABLE이면 점유 예약이 없고, HELD/SOLD면 반드시 있다.
-- 제약 없이 COMMENT로만 두면 "SOLD인데 reservation_id가 NULL"인 썩은 행이 생길 수 있다.
-- 선점·해제 UPDATE가 두 컬럼을 항상 한 번에 같이 쓰므로 걸림돌이 되지 않는다 (Task 022에서 검증).
--
-- 복합 FK는 등급과 회차가 어긋나는 것만 막는다. 좌석의 공연장이 회차 공연의 공연장과 같은지는
-- schedules → performances → venues로 3홉이라 FK로 표현할 수 없고, 검증 테스트로 커버한다.

CREATE TABLE reservation_seats (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id   bigint         NOT NULL REFERENCES reservations (id),
    schedule_seat_id bigint         NOT NULL REFERENCES schedule_seats (id),
    price            numeric(12, 0) NOT NULL CHECK (price >= 0),
    created_at       timestamptz    NOT NULL DEFAULT now(),
    updated_at       timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT uk_reservation_seats_reservation_seat UNIQUE (reservation_id, schedule_seat_id)
);
-- schedule_seat_id 단독 UNIQUE는 두지 않는다 — 취소된 예약도 이력으로 남기므로 같은 좌석이
-- 여러 예약 행에 등장하는 것이 정상이다 (docs/ERD.md 2절).
-- reservation_id 단독 인덱스도 만들지 않는다 — 위 UNIQUE의 선두 컬럼이라
-- 좌석 반환 쿼리(WHERE reservation_id = :r)가 그 인덱스를 탄다.
-- fillfactor는 기본값 100을 쓴다. append-only라 같은 행을 반복 UPDATE하지 않으므로
-- 10%를 비워두면 저장 공간만 낭비하고 읽을 페이지 수가 늘어난다 (seats도 같은 이유로 기본값).

-- 한국어 COMMENT (docs/ERD.md 2절과 동일)

COMMENT ON COLUMN seats.id IS '고유 식별자(PK)';
COMMENT ON COLUMN seats.created_at IS '생성 일시';
COMMENT ON COLUMN seats.updated_at IS '수정 일시';
COMMENT ON TABLE seats IS '공연장의 물리적 좌석 배치 (venue 단위로 한 번만 정의, 회차와 무관)';
COMMENT ON COLUMN seats.venue_id IS '소속 공연장 (venues 참조)';
COMMENT ON COLUMN seats.section IS '구역 (등급별 좌·중앙·우 블록, 예: VIP-중, R-좌)';
COMMENT ON COLUMN seats.row_label IS '열 (무대에서 가까운 순서대로 1부터, 예: 1, 2, 23)';
COMMENT ON COLUMN seats.seat_number IS '구역 내 좌석 번호 (구역마다 1번부터 시작)';
COMMENT ON COLUMN seats.pos_x IS '좌석 배치도 상의 x 좌표 (UI 렌더링용, 블록 사이 통로만큼 비워둔다)';
COMMENT ON COLUMN seats.pos_y IS '좌석 배치도 상의 y 좌표 (UI 렌더링용, 작을수록 무대에 가깝다)';

COMMENT ON COLUMN schedule_seats.id IS '고유 식별자(PK)';
COMMENT ON COLUMN schedule_seats.created_at IS '생성 일시';
COMMENT ON COLUMN schedule_seats.updated_at IS '수정 일시';
COMMENT ON TABLE schedule_seats IS '회차별 좌석 재고 및 현재 상태 (seats를 회차마다 판매 단위로 인스턴스화)';
COMMENT ON COLUMN schedule_seats.schedule_id IS '소속 회차 (schedules 참조)';
COMMENT ON COLUMN schedule_seats.seat_id IS '물리적 좌석 (seats 참조)';
COMMENT ON COLUMN schedule_seats.ticket_grade_id IS '이 좌석에 매겨진 가격 등급 (ticket_grades 참조)';
COMMENT ON COLUMN schedule_seats.status IS '좌석 상태 (AVAILABLE: 예매 가능, HELD: 선점 중, SOLD: 결제 완료)';
COMMENT ON COLUMN schedule_seats.reservation_id IS '현재 이 좌석을 선점·구매한 예약 (reservations 참조, 비어있으면 AVAILABLE)';

COMMENT ON COLUMN reservation_seats.id IS '고유 식별자(PK)';
COMMENT ON COLUMN reservation_seats.created_at IS '생성 일시';
COMMENT ON COLUMN reservation_seats.updated_at IS '수정 일시';
COMMENT ON TABLE reservation_seats IS '예약이 거쳐간 좌석의 이력 (취소된 예약도 이력으로 남기는 append-only 기록)';
COMMENT ON COLUMN reservation_seats.reservation_id IS '소속 예약 (reservations 참조)';
COMMENT ON COLUMN reservation_seats.schedule_seat_id IS '배정된 회차별 좌석 (schedule_seats 참조)';
COMMENT ON COLUMN reservation_seats.price IS '이 좌석의 결제 시점 가격 스냅샷';
